### ISSUE TITLE
IPC issue

### ISSUE THREAD

**Issue by benoitpaillard** [TUDelft-DataDrivenControl/DRC_Fortran#2]
Hi all,

I suspect there is an issue with the IPC trigo projection here :

https://github.com/TUDelft-DataDrivenControl/DRC_Fortran/blob/b4eea60bf2f5d754fcb59b796d88ade79248cd83/Source/Functions.f90#L328-L329

I reckon rootMOOP should be outside of sin/cos parenthesis and is inside for the two first blades, but is indeed outside for third blade.

**Comment by spmulders** [comment]
Great suggestion Benoit, thank you! I will commit a fix.
